### ISSUE TITLE
No connection to Ap

### ISSUE THREAD

**Issue by Ghost-Talker** [jp112sdl/ShellyHMLOX#1]
Hallo 

bekomme leider nach dem Flashen und der Einrichtung über das Smartphone keine Verbindung zum AP (FritzBox). 
Passwort ist definitiv richtig. Auch Gastzugang mit "Gast" und "123456789" getestet. Ebenso DHCP.

Hier noch die Ausgabe aus dem ESP Loader wenn es hilft.

Speziell das "Already connected. Bailing out" irritiert mich.

> *WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Info
*WM: Sent info page
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Scan done
*WM: No networks found
*WM: Sent config page
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Scan done
*WM: No networks found
*WM: Sent config page
*WM: Request redirected to captive portal
*WM: Scan done
*WM: No networks found
*WM: Sent config page
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Scan done
*WM: No networks found
*WM: Sent config page
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Scan done
*WM: Home
*WM: -71
*WM: Sent config page
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: WiFi save
*WM: Parameter
*WM: ccu
*WM: 192.168.1.190
*WM: Parameter
*WM: loxudpport
*WM: 
*WM: Parameter
*WM: shelly
*WM: Shelly
*WM: Parameter
*WM: restorestate
*WM: 0
*WM: Parameter
*WM: gpio5mode_switch
*WM: 1
*WM: Parameter
*WM: custom_gpio5assender_switch
*WM: 
*WM: Parameter
*WM: backendtype
*WM: 0
*WM: Parameter
*WM: 
*WM: 
*WM: Parameter
*WM: custom_ip
*WM: 192.168.1.43
*WM: Parameter
*WM: custom_netmask
*WM: 255.255.255.0
*WM: Parameter
*WM: custom_gw
*WM: 192.168.1.1
*WM: static ip
*WM: 192.168.1.43
*WM: static gateway
*WM: 192.168.1.1
*WM: static netmask
*WM: 255.255.255.0
*WM: Sent wifi save page
*WM: Connecting to new AP
*WM: Connecting as wifi client...
*WM: Custom STA IP/GW/Subnet
*WM: 192.168.1.43
*WM: Connection result: 
*WM: 3
Should save config
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Already connected. Bailing out.
*WM: IP Address:
*WM: 192.168.1.43
Wifi Connected
CUSTOM STATIC IP: 0.0.0.0 Netmask: 0.0.0.0 GW: 0.0.0.0
Custom IP Address is set!
saving config
{"ip":"192.168.1.43","netmask":"255.255.255.0","gw":"192.168.1.1","ccuip":"192.168.1.190","shelly":"Shelly","restoreOldState":0,"backendtype":0,"loxudpport":"","gpio5mode":1,"gpio5assender":false}
 ets Jan  8 2013,rst cause:1, boot mode:(1,7)
 ets Jan  8 2013,rst cause:4, boot mode:(1,7)
wdt reset

**Comment by jp112sdl** [comment]
Laut Log ist aber alles korrekt...
Die Verbindung wird hergestellt.
Die feste IP ist `192.168.1.43`.

> Speziell das "Already connected. Bailing out" irritiert mich.

Weil mit den WLAN Zugangsdaten aus dem EEPROM schon erfolgreich eine Verbindung hergestellt werden konnte.
