### ISSUE TITLE
Eingestellt  :O  ? Und nun...?

### ISSUE THREAD

**Issue by Fiiti** [jp112sdl/ShellyHMLOX#4]
Hi,
Du stellst diese coole FW ein? Ich finde die wesentlich besser als Tasmota wegen des direkten Rückkanals.
Machst Du diese irgendwo anders weiter?

Gruß,
Fi

**Comment by jp112sdl** [comment]
Hi, nein ich mache da nichts weiter.

Aber die FW funktioniert ja... da muss man nicht dauernd was dran rumbasteln. ;-) 

Jedoch tauchen immer wieder neue Hardware-Rev. der Sonoff auf, bei denen manche scheinbar Probleme (i.b. beim Speichern der Konfigurationsdaten) machen. 

Da ich bei mir selbst keine WLAN-Aktoren mehr (neu) einsetze, ist hier dann auch schluss.
Vielleicht findet sich ja jemand und baut was Neues oder basierend hierauf weiter.

**Comment by Fiiti** [comment]
Die FW läuft super. Einzig mit Hostnamen kann es Probleme geben. Hatte den Hostnamen "shelly1-WZ-Tuer". Damit gibt es dann Probleme bei der Rückmeldung zur CCU.

**Letzte Frage: Hattest Du auch was für den 2Kanal Shelly gemacht oder sogar kompiliert?**

**Comment by jp112sdl** [comment]
Nein, nichts dergleichen
